apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - postgrest.yaml
  - gotrue.yaml
  - gateway.yaml
  - services.yaml
  - ingress.yaml
  - middleware-strip-prefix.yaml

commonLabels:
  app.kubernetes.io/part-of: supabase
