apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-layer

resources:
  - namespace.yaml
  - configmap.yaml
  - sgx-qcnl-configmap.yaml
  - services-deployment.yaml

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: service-layer
      app.kubernetes.io/managed-by: kustomize
